name: Draft a release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version number (e.g. 1.2.3) OR one of patch, minor, major (see https://github.com/wraithan/cargo-bump)'
        required: true
        default: 'patch'

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Stable with rustfmt and clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: cargo
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-bump
          version: latest
      - name: Update version
        id: updated_version
        shell: bash
        run: |
          cargo bump ${{ github.event.inputs.version }}
          version=$(cargo metadata --format-version=1 --no-deps | jq -r '.packages[0].version')
          echo ::set-output name="version::$version"
      - name: Update changelog
        id: changelog
        shell: bash
        run: |
          pip3 install python-kacl
          kacl-cli release ${{ steps.updated_version.outputs.version }} --modify --auto-link
          echo "" >> CHANGELOG.md
          body=$(kacl-cli get ${{ steps.updated_version.outputs.version }})
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name="body::$body"
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: 'CHANGELOG.md Cargo.toml'
          message: 'Release ${{ steps.updated_version.outputs.version }}'
      - name: Create tag
        run: |
          git tag ${{ steps.updated_version.outputs.version }}
          git push origin ${{ steps.updated_version.outputs.version }}
      - name: Create a draft release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.updated_version.outputs.version }}
          name: Release ${{ steps.updated_version.outputs.version }}
          body: ${{ steps.changelog.outputs.body }}
          draft: true
